### ISSUE TITLE
PDF Export Unknown Error Occurred (font missing?)

### ISSUE THREAD

**Issue by boxcomrob** [BookStackApp/BookStack#1112]
**Describe the bug**
When I try to export a page as a PDF, it shows "Unknown error occurred"
`ErrorException (E_WARNING)
fopen(/home/[redacted]/BookStack/app/vendor/dompdf/dompdf/lib/fonts//73a648e04197eba26eb65837ab386447.ufm): failed to open stream: No such file or directory`

**Steps To Reproduce**
1. Create a page (can be blank)
2. Click Export > PDF
3. See error

**Expected behavior**
Export a PDF file of the current page

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.24.1
 - PHP Version: 7.0
 - Hosting Method (Nginx/Apache/Docker): LiteSpeed 

**Additional context**
The content of this install was migrated from another testing server to this production one (same version) following the guides here: https://www.bookstackapp.com/docs/admin/backup-restore/
Only the URL has changed (I updated it in the database and .env where needed), but remains in the same format, This was otherwise a clean fresh install from Git.

From browsing my folder structure, the location reported in the error message is the wrong location. My folder structure does not seem to include the /app/ section at the beginning. The fonts (not one by the referenced name though) exist in: BookStack/vendor/dompdf/dompdf/lib/fonts
Where should I update this path?

**Comment by boxcomrob** [comment]
Apologies I had missed #1097 when I posted this. Appears to be the same problem. Hopefully my additional info here about the paths will help both of us

**Comment by derek-shnosh** [comment]
I am having a similar issue, if not the same. I have a custom embedded font that breaks PDF export.

Worth noting that to embed the font, I placed the files in the **/storage/uploads/images/fonts/** directory, because when they were in **/storage/fonts/** I'd get JS errors about being unable to load it that I have no idea how to resolve 🤦‍♂️.

Then in custom HTML head content I placed the following;
```css
<style>
  @font-face {
    font-family: 'FontName';
    src: url('../../../uploads/images/fonts/FontName.woff2') format('woff2'),
         url('../../../uploads/images/fonts/FontName.woff') format('woff'),
         url('../../../uploads/images/fonts/FontName.ttf') format('truetype');
  }
  body {
    font-family: 'FontName', sans-serif;
  }
</style>
```

This works fine for viewing the document, but I get the Unknown Error when trying to PDF export using WKHTMLtoPDF, I get the following;

```
[2018-11-21 19:22:05] production.ERROR: The exit status code '1' says something went wrong:
stderr: "Loading pages (1/6)
Error: Failed to load file:///uploads/images/fonts/FontName.woff, with network status code 203 and http status code 0 - Error opening /uploads/images/fonts/FontName.woff: No such file or directory
...

command: /usr/local/bin/wkhtmltopdf --lowquality --print-media-type '/tmp/knp_snappy5bf5b05cac59a9.27922005.html' '/tmp/knp_snappy5bf5b05cac6724.14389349.pdf'. {"userId":3,"email":"omitted","exception":"[object] (RuntimeException(code: 0): The exit status code '1' says something went wrong:
Error: Failed to load file:///uploads/images/fonts/FontName.woff, with network status code 203 and http status code 0 - Error opening /uploads/images/fonts/FontName.woff: No such file or directory
```
