### ISSUE TITLE
Sorting a Book breaks bookstack

### ISSUE THREAD

**Issue by aiveras** [BookStackApp/BookStack#1526]
Every time you move a page in a book, the book disappears and you get an error message with "Book not found".
We used version 0.26.2
Every time we want to move a page in an already existing book in the order and press save the book disappears. However, the pages can still be found. Also the URL still shows the book name. But as soon as you only want to display the book the error message will be displayed. 

How do I get the book back?

**Comment by ssddanbrown** [comment]
Hi @aiveras,
Sorry to hear you are having some troubles. This is not something I've been able to re-produce. 

Does this occur when using an admin account?
Do you have any details on how you are hosting BookStack or how BookStack was installed?

**Comment by aiveras** [comment]
Hi @ssddanbrown ,

we hosted bookstack as docker-compose. So far the error happened twice in both cases an admin account was used. Whether it also happens without admin account I don't know but could test it out.
Is there a way to display logs in bookstack?

**Comment by ssddanbrown** [comment]
@aiveras Details on debugging [can be found here](https://www.bookstackapp.com/docs/admin/debugging/). Can you provide any details on the docker-compose setup? Such as the containers you are using?

**Comment by aiveras** [comment]
@ssddanbrown thank you very much for the link. I enabled now debugging. Below you see the used docker-compose.yml 
```
version: '2'

services:

  db:
    container_name: bookstack-mariadb
    image: mariadb:10.4.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: bookstack-db
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: 'secret'
    volumes:
      - /opt/docker/bookstack/mysql:/var/lib/mysql

  redis:
    container_name: bookstack-redis
    image: redis:5.0.4
    restart: unless-stopped


  app:
    container_name: bookstack
    build: .
    depends_on:
      - db
    restart: unless-stopped
    environment:

      - APP_DEBUG=true

      - APP_URL=https://domain.tld

      - STORAGE_TYPE=local_secure

      - MAIL_DRIVER=smtp
      - MAIL_HOST=mail.domain.tld
      - MAIL_PORT=465
      - MAIL_USERNAME=email@domain.tld
      - MAIL_PASSWORD='secret'
      - MAIL_ENCRYPTION=ssl
      - MAIL_FROM=email@domain.tld

      - DB_HOST=db
      - DB_DATABASE=bookstack-db
      - DB_USERNAME=bookstack
      - DB_PASSWORD=secret

      - AUTH_METHOD=ldap
      - LDAP_SERVER=ldap.domain.tld:1389
      - LDAP_BASE_DN=ou=people,dc=ldap,dc=domain,dc=tld
      - LDAP_DN=uid=client,ou=admins,dc=ldap,dc=domain,dc=tld
      - LDAP_PASS=secret
      - LDAP_USER_FILTER="(&(|(uid=$${user})(mail=$${user}))(isMemberOf=cn=[Access] BookStack,ou=groups,dc=ldap,dc=domain,dc=tld))"
      - LDAP_EMAIL_ATTRIBUTE=mail
      - LDAP_USER_TO_GROUPS=true
      - LDAP_GROUP_ATTRIBUTE=isMemberOf
      - LDAP_REMOVE_FROM_GROUPS=true

      - VIRTUAL_HOST=domain.tld
      - LETSENCRYPT_HOST=domain.tld
      - LETSENCRYPT_EMAIL=email@domain.tld

      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_SERVERS=bookstack-redis:6379:0

    volumes:
      - /opt/docker/bookstack/bookstack/public-uploads:/var/www/bookstack/public/uploads
      - /opt/docker/bookstack/bookstack/storage-uploads:/var/www/bookstack/storage/uploads
    networks:
      - default
      - proxy-tier

networks:

  proxy-tier:
    external:
      name: nginx-proxy
```
I was able to narrow the error down further. It doesn't matter if an admin account moves pages or a normal user. The error always occurs when there are enough pages and chapters so that you have to scroll when sorting. With small books with for example 4-10 pages and 1-2 chapters it does not happen. As a test I created a longer book with 6 chapters and 2-3 pages each. Here is the log file of the Docker-compose:

```
bookstack | bookstack.dev:80 172.18.0.5 - - [06/Jul/2019:13:42:21 +0000] "GET /books/test/sort HTTP/1.1" 200 23744 "https://domain.tld/books/test/sort" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
bookstack | bookstack.dev:80 172.18.0.5 - - [06/Jul/2019:13:42:21 +0000] "GET /translations HTTP/1.1" 200 6524 "https://domain.tld/translations" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
bookstack | bookstack.dev:80 172.18.0.5 - - [06/Jul/2019:13:42:22 +0000] "GET /ajax/search/entities?types=book&permission=update HTTP/1.1" 200 2526 "https://domain.tld/ajax/search/entities?types=book&permission=update" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
bookstack | bookstack.dev:80 172.18.0.5 - - [06/Jul/2019:13:42:32 +0000] "POST /books/test/sort HTTP/1.1" 302 1319 "https://domain.tld/books/test/sort" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
bookstack | [Sat Jul 06 13:42:34.106067 2019] [php7:notice] [pid 123] [client 172.18.0.5:57392] [2019-07-06 13:42:34] production.ERROR: Book not found {"userId":4,"email":"forename.surename@domain.tld","exception":"[object] (BookStack\\\\Exceptions\\\\NotFoundException(code: 404): Book not found at /var/www/bookstack/app/Entities/Repos/EntityRepo.php:162)"} [], referer: https://domain.tld/books/test
bookstack | bookstack.dev:80 172.18.0.5 - - [06/Jul/2019:13:42:33 +0000] "GET /books/test HTTP/1.1" 500 1227180 "https://domain.tld/books/test" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
bookstack-mariadb | 2019-07-06 13:39:36 0 [Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
bookstack-mariadb | 2019-07-06 13:39:36 0 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
bookstack-mariadb | 2019-07-06 13:39:37 189 [ERROR] Transaction not registered for MariaDB 2PC, but transaction is active

```
For security reasons I have changed all passwords and domains tlds as well as email addresses.
