### ISSUE TITLE
Helm Charts - Configurable Third Party Authentication

### ISSUE THREAD

**Issue by mjschmidt** [BookStackApp/BookStack#1677]
Again another helm chart addition for configuration it would be nice to pass the elements found here via the values file:
https://www.bookstackapp.com/docs/admin/third-party-auth/#gitlab

**Comment by ssddanbrown** [comment]
Hi @mjschmidt,
Thanks for the request but we don't officially support helm charts as part of this core project repo.
I don't really know helm but if you're able to pass the values as environment variables then you should be good. 

Since we don't support helm I'm going to close this as out-of-scope.

**Comment by mjschmidt** [comment]
@ssddanbrown You all own the helm repo at that link. Look all you have to do is replace contents of the index file found at [this link](https://charts.rook.io/release)

With the following. I did it in literally 2 seconds in a notepad by finding and replacing the old icon image with the correct link to the image.

My guess is who ever is unofficially pushing into the rook.io helm repo is just copying and pasting the old index file so this isn't anything that actually requires support.
```
apiVersion: v1
entries:
  rook-ceph:
  - apiVersion: v1
    created: 2019-09-20T22:18:58.509063113Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: 6dbaeb1846d57e5e5344b9b6d9eb4674d3c02e70a191c141bbb9f599f4f6390a
    icon: https://rook.io/images/rook-logo.svg
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.1.1.tgz
    version: v1.1.1
  - apiVersion: v1
    created: 2019-09-20T22:18:58.508423006Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: 341da3d793da87fe8c73751df0a533da76658cb893578e03320c60a4989f62cd
    icon: https://rook.io/images/rook-logo.svg
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    created: 2019-09-20T22:18:58.507810671Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: 357efbee679644c14efb456b121ba7ec3b3d580065670ce803ecade1cbb63160
    icon: https://rook.io/images/rook-logo.svg
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.6.tgz
    version: v1.0.6
  - apiVersion: v1
    created: 2019-09-20T22:18:58.507365783Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: ff0023868dd716cf68c20f5d73ab5b67537af04eb9565e61449f4c063ac4c98e
    icon: https://rook.io/images/rook-logo.svg
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.5.tgz
    version: v1.0.5
  - apiVersion: v1
    created: 2019-09-20T22:18:58.506927839Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: 1337d2b0f47b7044c749ac4435a689ca61045e429d41fc6c92e24011338d906b
    icon: https://rook.io/images/rook-logo.svg
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.4.tgz
    version: v1.0.4
  - apiVersion: v1
    created: 2019-09-20T22:18:58.506485629Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: 979991482ecb15638633cb1419c44e05c780fff36f7b33f4f537d4b1f3a3bc13
    icon: https://rook.io/images/rook-logo.svg
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.3.tgz
    version: v1.0.3
  - apiVersion: v1
    created: 2019-09-20T22:18:58.506051112Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: d13ee2111d106f7770e9392d6a59416a0bf20ad4d3f7b699d3ed084157fdf7e1
    icon: https://rook.io/images/rook-logo.svg
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.2.tgz
    version: v1.0.2
  - apiVersion: v1
    created: 2019-09-20T22:18:58.50566559Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: 174f4a609167535d952fb5f7fa4f75a4dc92ed923e1f905351f4d25aa3e94890
    icon: https://rook.io/images/rook-logo.svg
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.1.tgz
    version: v1.0.1
  - apiVersion: v1
    created: 2019-09-20T22:18:58.505286469Z
    description: File, Block, and Object Storage Services for your Cloud-Native Environment
    digest: 6f1c280b177e42c970e9593e20b2bdc7c2f191fdb532cb1b3e16db84c0100a6e
    icon: https://rook.io/images/rook-logo.svg
    name: rook-ceph
    sources:
    - https://github.com/rook/rook
    urls:
    - https://charts.rook.io/release/rook-ceph-v1.0.0.tgz
    version: v1.0.0
generated: 2019-09-20T22:18:58.504761531Z
```
