### ISSUE TITLE
Kubernetes DB access issues

### ISSUE THREAD

**Issue by timeandtimeago** [BookStackApp/BookStack#1776]
**Describe the bug**
I am having trouble getting bookstack to recognize the database configuraation env vars for kub. 
I get an error printout with permission denied - but it does not reflect the correct user configured in the env vars. 

I know the env vars are infact working because the `APP_DEBUG` var is taking and it is printing out debug logs. 

Any help or tips on this would be greatly appreciated!

Kub Manifest:
```
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "bookstack-test-x5"
  namespace: "default"
  labels:
    app: "bookstack-test-x5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "bookstack-test-x5"
  template:
    metadata:
      labels:
        app: "bookstack-test-x5"
    spec:
      containers:
      - name: "bookstack-sha256"
        image: "gcr.io/<PATH_TO_MY_CONTAINER>"
        env:
        - name: "DB_USER"
          value: "bookstack22"
        - name: "DB_HOST"
          value: "127.0.0.1"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "bookstack"
        - name: "DB_PSWD"
          value: "my_secret_passowrd"
        - name: "APP_DEBUG"
          value: "true"
        - name: CACHE_DRIVER
          value: "database"
        - name: SESSION_DRIVER
          value: "database"
```

Logs output:
```
wait-for-db: waiting for 127.0.0.1:3306
wait-for-db: done
Do not run Composer as root/super user! See https://getcomposer.org/root for details
> php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
> php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');"
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: barryvdh/laravel-snappy
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/socialite
Discovered Package: nesbot/carbon
Discovered Package: socialiteproviders/manager
Package manifest generated successfully.
> php artisan cache:clear
[2019-11-12 01:30:33] production.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'cloudsqlproxy~104.154.238.134' (using password: YES) {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'cloudsqlproxy~104.154.238.134' (using password: YES) at /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'cloudsqlproxy~104.154.238.134' (using password: YES) at /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2019-11-12 01:30:33] production.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'cloudsqlproxy~104.154.238.134' (using password: YES) (SQL: delete from `cache`) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'cloudsqlproxy~104.154.238.134' (using password: YES) (SQL: delete from `cache`) at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'cloudsqlproxy~104.154.238.134' (using password: YES) at /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'cloudsqlproxy~104.154.238.134' (using password: YES) at /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []

                                                                               
  [Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'cloudsqlproxy~10  
  4.154.238.134' (using password: YES) (SQL: delete from `cache`)              
                                                                               

                                                                               
  [Doctrine\DBAL\Driver\PDOException]                                          
  SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'cloudsqlproxy~10  
  4.154.238.134' (using password: YES)                                         
                                                                               

                                                                               
  [PDOException]                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'cloudsqlproxy~10  
  4.154.238.134' (using password: YES)                                         
                                                                               

Script php artisan cache:clear handling the post-install-cmd event returned with error code 1
```
