### ISSUE TITLE
New Line in List After Sub-List Creates New Paragraph Block

### ISSUE THREAD

**Issue by techmattr** [BookStackApp/BookStack#1911]
Create List

1. Thing 1
2. Thing 2
    1. Sub-Thing 1
    2. Sub-Thing 2

3. Thing 3

While editing a list or ordered list a new line should remain in the same block unless you Enter twice. There is no way to break out of the sub-list and maintain the paragraph block for the next item in the main list.

**Comment by techmattr** [comment]
Apparently GitHub is even worse at this. Here is screenshot example from BookStack: https://i.imgur.com/R9t39Yy.png

**Comment by MikeyMJCO** [comment]
Just to be clear the input looks like this:

``` md
1. Thing 1
2. Thing 2
  1. Sub-Thing 1
  2. Sub-Thing 2
3. Thing 3
```

**Comment by MikeyMJCO** [comment]
Aha - think I've found the culprit.

The HTML markup for the above is entirely correct.

``` html
<ol>
<li>Thing 1</li>
<li>Thing 2
<ol>
<li>Sub-Thing 1</li>
<li>Sub-Thing 2</li>
</ol>
</li>
<li>Thing 3</li>
</ol>
```

The issue is the CSS which has the following:
``` css
p, ul, ol, pre, table, blockquote {
    margin-top: 0.3em;
    margin-bottom: 1.375em;
}
```
So at the end of the nested `ol` (the sub-list) the CSS is adding enough padding so as to appear to have a newline. The markdown is rendering to the correct HTML.

**Comment by MikeyMJCO** [comment]
What's needed here is a rule to stop nested lists getting the padding. e.g:
``` css
li > ul {
    margin-block-start: 0px;
    margin-block-end: 0px;
}
```
plus
```
li > ol {
    margin-block-start: 0px;
    margin-block-end: 0px;
}
```
this gives us this output:
![image](https://user-images.githubusercontent.com/2288257/74938665-56ad4180-53e6-11ea-8a1f-609a9df58684.png)

**Comment by MikeyMJCO** [comment]
**Side-note:** GitHub is just being stupid at this - they are wrapping the text for each `<li>` element in a `<p>` tag providing the paragraph padding.

**Comment by techmattr** [comment]
That does seem to mostly fix it. There are still a few extra vertical pixels between **sub-thing b** and **thing c** but it doesn't look completely off anymore.

![bQF6EdN](https://user-images.githubusercontent.com/12102155/74941317-d0cacf80-53c0-11ea-816f-dffbdb84cdfe.png)

**Comment by MikeyMJCO** [comment]
So there are... now here we have a problem. OCD essentially means I'm now going to find out where they are coming from and fix them.. Thanks for that :-p

**Comment by techmattr** [comment]
Hah. Yeah that's really strange. I'm using Firefox and Stylus to render the CSS so it could be something with either of those...

**Comment by MikeyMJCO** [comment]
Maybe adding 
```
padding-block-start: 0;
padding-block-end: 0;
```
would help.

So the full CSS rule could be:

``` css
li > ol, li > ul {
    margin-block-end: 0px;
    margin-block-start: 0px;
    padding-block-end: 0px;
    padding-block-start: 0px;
}
```
