### ISSUE TITLE
Markdown editor: hide and/or resize the preview pane

### ISSUE THREAD

**Issue by marcvef** [BookStackApp/BookStack#2215]
**Describe the feature you'd like**
I love the markdown mode. The preview pane while editing the markdown source pane is a nice touch. However, most of the time markdown is already readable enough that a preview pane is not necessary. I don't mind having it enabled when BookStack can use the full monitor screen size, but if I put the browser page on only the left/right half of the screen, the preview pane is quite obstructive because the source pane is only covering 1/4 of the screen.

It would be nice to have a button to simply disable the preview pane letting the source pane use 100% of the available screen width. Or even better yet, allow a slider between the panes to dynamically adjust the width of both to the point were either one can be completely hidden to view the other pane at 100% width.

I have been able to simply modify the DOM to achieve hiding the preview pane by deleting the preview pane node and adjusting the source pane width from 50% to 100%.

**Describe the benefits this feature would bring to BookStack users**
Such a feature would benefit people with one monitor (such as laptops) who use BookStack on one half of the screen and another type of content on the other, e.g., to write notes while reading a PDF.

**Comment by alderson59** [comment]
+1

**Comment by abulgatz** [comment]
+1

In the meantime I have added this CSS as a user style in [Stylus](https://github.com/openstyles/stylus) that I can easily enable or disable.

```css
#markdown-editor .markdown-editor-wrap {
    display: none;
}
#markdown-editor .markdown-editor-wrap.active {
    display: flex;
    width: 100%;
    max-width: 100%;
}
```
