### ISSUE TITLE
scroll bar code blocks

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#2267]
BookStack 0.30.0

all code blocks now have a scroll bar
![image](https://user-images.githubusercontent.com/4026090/93896783-c7b13080-fd0a-11ea-9051-7de6ddff185e.png)

appeared after update

**Comment by MaxG-Git** [comment]
I have noticed this aswell, for the time being I have linked a css page (using the custom header settinngs) with the following to supress the scrollbar but would love to see a "real" solution 😊
```css
.CodeMirror-vscrollbar{
  overflow-y: hidden;
}
```
