### ISSUE TITLE
Use prefers-color-scheme to set light/dark mode by default

### ISSUE THREAD

**Issue by Baptistou** [BookStackApp/BookStack#2407]
**Describe the feature you'd like**
Set light/dark mode by default according to [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).
Moreover, if an .env variable is created (#2081), provide 3 values :
- ```light``` --> use light mode
- ```dark``` --> use dark mode
- ```auto``` --> mode based on prefers-color-scheme, set by default

**Describe the benefits this feature would bring to BookStack users**
Improve UX in the same way as language auto detection from user agent.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Baptistou.

I thought about using `prefers-color-scheme` when implementing dark mode but decided against it.  `prefers-color-scheme` is primarily built for use in CSS media queries. I'd want to provide the user an option to control the preference on BookStack, non-dependant on browser/OS setting, so straight away that means we can't use the media query directly. We could detect the `prefers-color-scheme` state with JavaScript and set the controlling parent class depending on value but now we're adding mixed front-end and back-end logic for this control which means things are getting more complex. Upon that we would have to provide some level of 'auto' control as suggested so now we're needing some more complex user-control than just the toggle-button(s) we have now.

To me I didn't deem the use of the `prefers-color-scheme` worth implementing. If the option was provided by the browser as a header, as the language is, it'd be a bit more open to it.

**Comment by Baptistou** [comment]
And what about delegating the light/dark mode implementation to client side ?
I see in the code that the mode button is sending a POST request to server ```/settings/users/toggle-dark-mode```.
This is a cost that could be avoided by handling the mode change directly in client side.
You even don't need JavaScript at all, the following is a working example with pure CSS :
```html
<body>
    <input type="radio" id="light-mode" name="mode">
    <label for="light-mode">Light Mode</label>
    <input type="radio" id="dark-mode" name="mode">
    <label for="dark-mode">Dark Mode</label>
    <main>
        <p>Hello World !</p>
    </main>
</body>
```
```css
@media (prefers-color-scheme: light){
    #light-mode:indeterminate, #light-mode:indeterminate+label {
        display: none
    }
    main {
        color: #444;
        background-color: #F2F2F2;
    }
    #dark-mode:checked~main {
        color: #AAA;
        background-color: #111;
    }
}

@media (prefers-color-scheme: dark){
    #dark-mode:indeterminate, #dark-mode:indeterminate+label {
        display: none
    }
    main {
        color: #AAA;
        background-color: #111;
    }
    #light-mode:checked~main {
        color: #444;
        background-color: #F2F2F2;
    }
}

#light-mode:checked, #light-mode:checked+label,
#dark-mode:checked, #dark-mode:checked+label {
    display: none
}
```
