### ISSUE TITLE
[Bug Report]: Getting a 404 on login page since 21.11

### ISSUE THREAD

**Issue by rparree** [BookStackApp/BookStack#3095]
### Describe the Bug

I tried updating to version 21.11.2, but when accessing the site and it redirects to `/bookstack/login` it shows "Page Not Found".

Bookstack is running in kubernetes and i am using the linuxserver images. From a few tests i found out:

does not work

ghcr.io/linuxserver/bookstack:version-v21.11
ghcr.io/linuxserver/bookstack:version-v21.11.2
ghcr.io/linuxserver/bookstack:version-v21.11.3

works

ghcr.io/linuxserver/bookstack:version-v21.10.1
ghcr.io/linuxserver/bookstack:version-v21.10.3

thanks.,

### Steps to Reproduce

change version from 21.10.x to 21.11.x 

### Expected Behaviour

Login page to be displayed

### Exact BookStack Version

21.11

### Hosting Environment

kubernetes with istio.

**Comment by ssddanbrown** [comment]
Hi @rparree,

> I tried updating to version 21.11.2, but when accessing the site and it redirects to /bookstack/login it shows "Page Not Found".

- What URL are you hosting BookStack on? Are you hosting at `/bookstack` or are you hosting at `/`?
- What is configured for the `APP_URL` option?

**Comment by rparree** [comment]
I am hosting on `/bookstack`, the `APP_URL` includes the full : `https://xxx.yyyy.com/bookstack`

tx.,

**Comment by ssddanbrown** [comment]
Thanks for confirming @rparree.
Do you have any detail on how requests are sent to the linuxserver container? Are you using a standard reverse proxy? If so can you share the configuration used?

**Comment by rparree** [comment]
I am using istio's virtualservice. 

This works fine up to version `v21.10.1`. I should also mention that the "not found" page is the styled one from bookstack. Meaning its css assets etc are successfully fetched

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookstack
spec:
  hosts:
    - xxxx.yyyy.com
  gateways:
    - kube-system/gw-public
  http:
    - route:
        - destination:
            host: bookstack-0
            port:
              number: 80
      match:
        - uri:
            prefix: /bookstack
      rewrite:
        uri: /
```
