### ISSUE TITLE
[Bug Report]: Google authentication stopped working

### ISSUE THREAD

**Issue by AvrumFeldman** [BookStackApp/BookStack#3100]
### Describe the Bug

I don't know when it started but got a notice from a user today that they cannot log into the bookstack instance, I tested and got the following error "An error has occurred"
![chrome_zMSmOIIobV](https://user-images.githubusercontent.com/42219106/145451843-861aa2c5-f561-49e5-baf3-88b5a5714bed.png)
 
Local login does work.
Another bookstack instance using the same google oauth application does work, so it seems to be something specific to this instance.

My Docker compose file (removed sensitive info)
```
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - TZ=America/New_York
      # container rights
      - PUID=1000
      - PGID=1000
      
      - SESSION_LIFETIME=1440
      
      # hardcoded URL for the server, required for google integration
      - APP_URL=http://bookstack.fake.com:6875
      
      # Google integrations
      - GOOGLE_APP_ID=<snip>
      - GOOGLE_APP_SECRET=<snip>
      - GOOGLE_SELECT_ACCOUNT=true
      - GOOGLE_AUTO_REGISTER=true
      - GOOGLE_AUTO_CONFIRM_EMAIL=true
      
      # DB settings
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=<snip>
      - DB_DATABASE=bookstackapp
      
      # Mail settings
      - MAIL_DRIVER=smtp
      - MAIL_FROM=<snip>
      - MAIL_FROM_NAME=<snip>
      - MAIL_HOST=<snip>
      - MAIL_PORT=<snip>
      - MAIL_USERNAME=<snip>
      - MAIL_PASSWORD=<snip>
      - MAIL_ENCRYPTION=tls
    volumes:
      - /srv/config/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<snip>
      - TZ=America/New_York
      - MYSQL_DATABASE=<snip>
      - MYSQL_USER=<snip>
      - MYSQL_PASSWORD=<snip>
    volumes:
      - /srv/config/bookstack/DB:/config
    restart: unless-stopped
```

### Steps to Reproduce

1. Log in using google account using a google account,

### Expected Behaviour

Login should succeed 

### Exact BookStack Version

v21.11

### Hosting Environment

Docker image linuxserver/bookstack
