### ISSUE TITLE
[Bug Report]: Multiple redirects on starting page if installation is in subfolder

### ISSUE THREAD

**Issue by FastHogi** [BookStackApp/BookStack#3164]
### Describe the Bug

I'm using bookstack in a docker container and use nginx as my reverse proxy to be able to access bookstack from a subfolder URL mydomain.com/bookstack. If you open the developer tools in a browser and have a closer look at the network requests, you will see multiple redirects with multiple trailing slashes when you try to access the starting page (see screenshot). You can also see the multiple slashes in the address bar of the browser (https://mydomain.com/bookstack///////////////////).

This only happens on the starting page. All other pages do not show this behavor and bookstack is still usable. If you click on the bookmark logo left to the search pane, you will be redirected to the starting page, which will show this behavior again.

I added the subfolder path in my local `.env` file:
`APP_URL=https://mydomain.com/bookstack`

My nginx location block looks like this:
```
location /bookstack {
    # redirect to same location with a trailing slash
    return 301 $scheme://$host$request_uri/;
}
location /bookstack/ {
    proxy_pass http://192.168.1.20:6875/;
}
```

My docker-compose file for running bookstack in a docker container looks like this:

```
version: '3'
services:
  bookstack:
    container_name: bookstack
    image: lscr.io/linuxserver/bookstack
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: https://mydomain.com/bookstack
      DB_HOST: bookstack_db
      DB_USER: bookstack
      DB_PASS: ${PASSWORD_MYSQL_BOOKSTACK}
      DB_DATABASE: bookstack
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/bookstack:/config
    networks:
      - CustomNet_Bookstack
    ports:
      - 6875:80
    healthcheck:
      test: wget --spider http://localhost/status || exit 1
      interval: 60s
      timeout: 10s
      retries: 5    
    depends_on:
      bookstack_db:
          condition: service_started
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    restart: always
    container_name: bookstack_db
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: ${PASSWORD_MYSQL_ROOT}
      TZ: Europe/Berlin
      MYSQL_DATABASE: bookstack
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: ${PASSWORD_MYSQL_BOOKSTACK}
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - /data/bookstack:/config
    networks:
      - CustomNet_Bookstack
    healthcheck:
      test: mysqladmin ping --user=root --password=${PASSWORD_MYSQL_ROOT} || exit 1
      interval: 60s
      timeout: 10s
      retries: 5    
networks:
  CustomNet_Bookstack:
    name: CustomNet_Bookstack
```

### Steps to Reproduce

1. install bookstack from the above docker-compose file in a docker container
2. add a subfolder location in nginx
3. open the developer tools on your browser
4. open the bookstack starting page mydomain.com/bookstack
5. look at the address bar or on the network tab of the developer tools 

### Expected Behaviour

No multiple redirects on starting page.

### Screenshots or Additional Context

![grafik](https://user-images.githubusercontent.com/41678833/149469083-fc68f5f4-b167-4483-9176-5c9686757b4d.png)

### Exact BookStack Version

v21.12.2

### PHP Version

7.4.26

### Hosting Environment

- Ubuntu Server 21.10 running on a raspberry pi4 (4 GB)
- Docker engine 20.10.12
- Latest docker image from [https://hub.docker.com/r/linuxserver/bookstack](https://hub.docker.com/r/linuxserver/bookstack)
