### ISSUE TITLE
[Bug Report]: Custom HTML Head Content not working

### ISSUE THREAD

**Issue by SimpelMe** [BookStackApp/BookStack#3191]
### Describe the Bug

Any style code written into "Custom HTML Head Content" I tested is not executed. 
Second I couldn't find this style in \<head\> except:
```css
<style id="custom-styles" data-color="#555555" data-color-light="rgba(85,85,85,0.15)">
    :root {
        --color-primary: #555555;
        --color-primary-light: rgba(85,85,85,0.15);
        --color-bookshelf: #555555;
        --color-book: #555555;
        --color-chapter: #808080;
        --color-page: #808080;
        --color-page-draft: #808080;
    }
</style>
```

### Steps to Reproduce

1. go to /settings#customization
2. write css into section "Custom HTML Head Content" like:
```css
<style>
// underline all links in article
.card a, a.postlink {
  text-decoration: underline !important;
}
</style>
```
3. save and watch an article with a link inside

### Expected Behaviour

Link should be underlined.
That style should be written to \<head\>.

### Screenshots or Additional Context

I'm not totally sure but I think I introduced that style in v21.12.1 or v21.12 to my wiki and it worked.

### Exact BookStack Version

v21.12.2

### PHP Version

7.4.25 cli

### Hosting Environment

- 5.10.27-gentoo
- no proxy
