### ISSUE TITLE
Draw.io Diagrams.net - Inline images disapearing

### ISSUE THREAD

**Issue by securenotebook** [BookStackApp/BookStack#3533]
### Describe the Bug

Hi, 

I'm running into an issue when I create a diagram using the drawing button via the embedded drawing editor. 

Everything else is working great. 

Running via Docker Compose: https://github.com/linuxserver/docker-bookstack/pkgs/container/bookstack 

When I create the drawing, I can see a new folder created within the container and the image exists. 

root@fd691f82f262:/# cd /config/www/uploads/images/drawio/
root@fd691f82f262:/config/www/uploads/images/drawio# ls
2022-06
root@fd691f82f262:/config/www/uploads/images/drawio# cd 2022-06/
root@fd691f82f262:/config/www/uploads/images/drawio/2022-06# ls
drawing-1-1656208598.png  drawing-1-1656208685.png
root@fd691f82f262:/config/www/uploads/images/drawio/2022-06#

The source code for the previous image reveals this path from last month - now that path no longer exists  - I'm unsure if the folder is expiring, getting overwritten 

http://192.168.1.155:6875/uploads/images/drawio/2022-05/drawing-1-1653637858.png

As I type this, I realize it may be a bug with the linuxserver image - however, I'd like to share in case anyone runs into this issue.  After rebooting the container, 2022-06 folder is retained. 

### Steps to Reproduce

1. Create a Page
2. Create a new diagram via the Drawing button
3. Save Page
4. Edit Page - Double click on Diagram - it can be edited 
5. After some time ( after the update or new release ) - the image path is no longer valid 

### Expected Behaviour

Image preview should persist in /config/www/uploads/images/drawio/ and the drawio file be editable at a later date

### Screenshots or Additional Context

When first Created - everything works as expected:
![image](https://user-images.githubusercontent.com/734683/175796180-f67d18ec-ac98-4c24-96bc-4afb2f6cbff5.png)

### Browser Details

Chrome

### Exact BookStack Version

BookStack v21.10.2

### Hosting Environment

OS: Unraid
Docker-compose:  https://github.com/linuxserver/docker-bookstack/pkgs/container/bookstack

**Comment by ssddanbrown** [comment]
Hi @securenotebook,
Are you mounting the `/config` container as a volume as per the guidance for that container?

**Comment by securenotebook** [comment]
Hi Dan,

thanks for the follow-up,  yes I copied the docker-compose file per below:

I should have changed "/path/to/data" to something more meaningful - however, the volume exists and i can see the data

```
root@Tower:/path/to/data# ll
total 4.0K
   0 drwxr-xr-x 9 root        1000 200 Jun  5 14:16 ./
   0 drwxr-xr-x 3 root        root  60 Jun  5 14:16 ../
4.0K -rw-r--r-- 1 root        1000  52 Jun  5 14:16 BOOKSTACK_APP_KEY.txt
   0 drwxr-xr-x 2 root        root  40 Jun  5 14:16 custom-cont-init.d/
   0 drwxr-xr-x 2 root        root  40 Jun  5 14:16 custom-services.d/
   0 drwxr-xr-x 2 root        1000  80 Jun  5 14:16 keys/
   0 drwxr-xr-x 4 root        1000 100 Jun 26 10:00 log/
   0 drwxrwxr-x 3 root        1000  80 Jun  5 14:16 nginx/
   0 drwxr-xr-x 2 root        1000  80 Jun  5 14:16 php/
   0 drwxrwxr-x 5 root        1000 160 Jun 26 10:34 www/
```

```yaml
version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=password
      - DB_DATABASE=bookstackapp
    volumes:
      - /path/to/data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
```
