### ISSUE TITLE
No application encryption key has been specified.

### ISSUE THREAD

**Issue by dd-gamer** [BookStackApp/BookStack#3622]
### Describe the Bug

I'm trying to setup bookstack in docker, but can't get further than the error "" after loading the webinterface. It's running on top of a Raspberry Pi 4b. This is my docker-compose file:

<details>

```yaml
---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://192.168.0.126:6875
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=xxx
      - DB_DATABASE=bookstackapp
      - APP_DEBUG=true
    volumes:
      - /home/pi/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=xxx
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=xxx
    volumes:
      - /home/pi/bookstack:/config
    restart: unless-stopped
```

</details>

After opening the webinterface, I'm welcomed with: 
Error
Illuminate\Encryption\MissingAppKeyException
No application encryption key has been specified.

After some googling, I found out that it has something to do with artisan. But when I connect into the container over bash and run 'php artisan', it tells me 'Could not open input file: artisan'.

Does anyone knows a fix for this?

### Steps to Reproduce

1. Load docker-compose on pi4
2. Go to webinterface

### Expected Behaviour

Error
Illuminate\Encryption\MissingAppKeyException
No application encryption key has been specified.

### Exact BookStack Version

v22.07.1

### PHP Version

7.4.26

### Hosting Environment

Docker on pi4b
