### ISSUE TITLE
Undefined variable $cspNonce 

### ISSUE THREAD

**Issue by AidasK** [BookStackApp/BookStack#4153]
### Describe the Bug
```
2023/04/02 07:53:03 [error] 303#303: *72606 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined variable $cspNonce in /app/www/storage/framework/views/872733693c1f8e7d46945825e715cc42e8efb276.php:68
Stack trace:
#0 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /app/www/storage/framework/views/872733693c1f8e7d46945825e715cc42e8efb276.php(68): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')
#3 /app/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#4 /app/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#5 /app/www/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\View...PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined variable $cspNonce in /app/www/storage/framework/views/872733693c1f8e7d46945825e715cc42e8efb276.php:68
Stack trace:
#0 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /app/www/storage/framework/views/872733693c1f8e7d46945825e715cc42e8efb276.php(68): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')
#3 /app/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#4 /app/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Vie
```

```php
    <div component="back-to-top" class="back-to-top print-hidden">
        <div class="inner">
            <?php echo icon('chevron-up'); ?> <span><?php echo e(trans('common.back_to_top')); ?></span>
        </div>
    </div>

    <?php echo $__env->yieldContent('bottom'); ?>
    <script src="<?php echo e(versioned_asset('dist/app.js')); ?>" nonce="<?php echo e($cspNonce); ?>"></script>
    <?php echo $__env->yieldContent('scripts'); ?>

    <?php echo $__env->make('layouts.parts.base-body-end', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
</body>
</html>
```
68 line is `<script src="<?php echo e(versioned_asset('dist/app.js')); ?>" nonce="<?php echo e($cspNonce); ?>"></script>`

### Steps to Reproduce

Not sure, just happened after I have renamed an article title.

### Expected Behaviour

No errors should be reported

### Exact BookStack Version

BookStack v23.02.1

### PHP Version

8.0

### Hosting Environment

Docker installation via https://hub.docker.com/r/linuxserver/bookstack

**Comment by ssddanbrown** [comment]
Hi @AidasK,

- Is this consistently reproducible? 
- Can you provide the exact version of the BookStack container image in use?
- Do you have any example config of your setup (`docker-compose.yml`) and/or can you describe your docker/hosting environment a bit?

**Comment by AidasK** [comment]
This starts to happen everytime and lasts for a bit if:
 - I rename an article and url changes.
 - I come to the old url and page just crashes.
 - If I visit other urls everything is still crashing with 500 error code.
 - After some time probably cookie expires and everything works as before.
 
 This is my build https://hub.docker.com/layers/linuxserver/bookstack/23.02.1/images/sha256-3626275c7b1af92e98dc7ffc8bf5eda6bf4ff3ca7c4c09e91f137ca47581c1ff?context=explore
 
 This is my compose file:
 ```yml
---
version: "3.9"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://wiki.website.com
      - DB_HOST=qqqqq
      - DB_USER=qqqqq
      - DB_PASS=qqqq
      - DB_DATABASE=qqqq
      - VIRTUAL_HOST=wiki.website.com
      - SELF_SIGNED_HOST=wiki.website.com
    volumes:
      - ./data:/config
    ports:
      - "80:80"
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./docker-nginx.conf:/etc/nginx/conf.d/my_proxy.conf

  proxy-companion:
    container_name: proxy-companion
    restart: always
    image: sebastienheyd/self-signed-proxy-companion
    volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certs:/etc/nginx/certs:rw
```

Wiki is running on cloudflare cdn which routes to our server via self signed certificate.
