### ISSUE TITLE
SQLSTATE Connection Refused

### ISSUE THREAD

**Issue by samundo** [BookStackApp/BookStack#4158]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I tried to load Bookstack web interface via IP and I got a site not reachable. I use watchtower to update Bookstack. I noticed on the container log files it said new config files. I loaded the new config files and those errors disappeared. Now when I load the web interface via IP I get a white page. In the container log I now get this error saying Connect Refused as you can see from error in container logs below. Any suggestions on what/how to fix this?

### Exact BookStack Version

Not Sure cannot load interface

### Log Content

<details><summary>Details</summary>
<p>

```
using keys found in /config/keys
App Key found - setting variable for seds
Running config - DB_HOST set
Waiting for DB to be available
   Illuminate\Database\QueryException 
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = bookstackapp and table_name = migrations and table_type = 'BASE TABLE')
  at /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
    756▕         // If an exception occurs when attempting to run a query, we'll format the error
    757▕         // message to include the bindings with SQL, which will make this exception a
    758▕         // lot more helpful to the developer instead of just the database's errors.
    759▕         catch (Exception $e) {
  ➜ 760▕             throw new QueryException(
    761▕                 $query, $this->prepareBindings($bindings), $e
    762▕             );
    763▕         }
    764▕     }
      +39 vendor frames 
  40  /app/www/artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

</p>
</details> 

### PHP Version

??

### Hosting Environment

Ubuntu 20.04.2, VPS.
Installed by docker compose script

**Comment by ssddanbrown** [comment]
Hi @samundo,
Generally an error of `SQLSTATE[HY000] [2002] Connection refused` means the app simply can't connect to the database at all. Might just not have network visibility.

Could be due to wrong `DB_*` options used in BookStack. Could be networking issue.
If you could provide a copy of your docker-compose file (With any secrets redacted) that would be helpful.

> I loaded the new config files

What do you exactly mean by this? What exact steps/files did you touch?

**Comment by samundo** [comment]
Hi @ssddanbrown, Thanks for the quick reply. 

Docker-compose file below. I have customised it and was working for the paste year and stopped working in the last month. Not sure when as I have been overseas. I just got back and went to access my wiki and would not load.  

<details>

```
---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    #networks:
    #  - bookstack
    environment:
      - PUID=1000
      - PGID=1000
      #- APP_URL=[redacted]
      - APP_URL=https://wiki.samundo.com.au
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=[redacted]
      - DB_DATABASE=bookstackapp
      - MAIL_DRIVER=smtp
      # Host, Port & Encryption mechanism to use
      - MAIL_HOST=[redacted]
      - MAIL_PORT=25
      #- MAIL_ENCRYPTION=tls
      # Authentication details for your SMTP service
      #- MAIL_USERNAME=user@provider.tld
      #- MAIL_PASSWORD=onlyifneeded
      # The "from" email address for outgoing email
      - MAIL_FROM=wiki@samundo.com.au  
      # The "from" name used for outgoing email
      - MAIL_FROM_NAME=BookStack
    volumes:
      - /opt/bookstack:/config
    ports:
      #- 6875:80
      - 80:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    #networks:
    #  - bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=[redacted]
      - TZ=Australia/Perth
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=[redacted]
    volumes:
      - /opt/database:/config
    restart: unless-stopped
    
networks:
  default:
    external:
      name: bookstack
```

</details>


I have checked the containers and they are on the same network. 172.18.0.xx
I have checked the .env file and made sure details matched.

With this message 

_I loaded the new config files_

In the container console it came up with a message that the following files are old and there is new files. Not sure how to replicate the error as it has now gone since I loaded the new files.

Files that were old were
default.conf
nginx.conf
ssl.conf

I went in and renamed these files as old.xxx.conf moved the files to an archives folder. In the folder there was a new sample file. I copied that and then rename it to the above. Regenerated the container and the error disappeared. Then I was left with the SQL error only. If you need I could put the archive files back to generate the error. When the old files are there the web interface does not load. Once I changed the files to the new files the web interface loads but with white screen. Not sure if this is relevant.
