### ISSUE TITLE
Class "Book" not found

### ISSUE THREAD

**Issue by jkonecny75** [BookStackApp/BookStack#4210]
### Describe the Bug

After the update, some books report an error (see screenshot)

### Steps to Reproduce

- use IMG `lscr.io/linuxserver/bookstack:v21.12.5-ls1`
- create a book with pages
- update on IMG `lscr.io/linuxserver/bookstack:v22.11.1-ls60`
- displaying a book causes an error (pages are OK)

### Expected Behaviour

Show pages and books

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/19643783/235376482-a6df7606-d30b-4f1f-ad14-3576e9d28578.png)

### Browser Details

110.0 (64-bit) Linux

### Exact BookStack Version

v22.11.1

### PHP Version

8.1.14

### Hosting Environment

Ubuntu 20.04.4 LTS
docker-compose 1.25.4
docker 20.10.12

**Comment by jkonecny75** [comment]
[stack_trace.txt](https://github.com/BookStackApp/BookStack/files/11362427/stack_trace.txt)

**Comment by ssddanbrown** [comment]
Hi @jkonecny75, A few notes:

- Just an FYI, I do not manage the linuxserver container myself (Not an official part of the project) but happy to attempt to support.
- Can you try on the latest version of the container? Rather than one for an old release. There may have been issues which have since been patched.
- If possible, could you provide the `docker-compose.yml` config in use here so I can gain a full view of how the container is used, and how volumes are mapped?

**Comment by jkonecny75** [comment]
Hi @ssddanbrown, thank you for your willingness

I tried the last version as a first option. After the error 'Class "Book" not found' I tried individual versions from 21.12.5-ls1. 

Version v22.11.1-ls60 is the first version to throw this bug

_docker-compose.yaml_:
```yaml
version: "3"

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:v21.12.5-ls1
    #image: lscr.io/linuxserver/bookstack:v23.02.3-ls75
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL="https://wiki.ourcompany.loc"
      - APP_DEBUG=true
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstack
      - AUTH_METHOD=ldap
      - LDAP_SERVER="192.168.1.1"
      - LDAP_BASE_DN="dc=ourcompany,dc=loc"
      - LDAP_VERSION="3"
      - LDAP_ID_ATTRIBUTE=sAMAccountName
      - LDAP_USER_FILTER=(&(sAMAccountName=$${user}))
      - LDAP_EMAIL_ATTRIBUTE=mail
      - LDAP_DISPLAY_NAME_ATTRIBUTE=cn
      - LDAP_DN=auth@ad.ourcompany.loc
      - LDAP_PASS=ourPasswd
    volumes:
      - ./data:/config
    ports:
      - "443:443"
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - TZ=Europe/Prague
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    restart: unless-stopped
    volumes:
      - ./data/:/config
```
