### ISSUE TITLE
504 Gateway Time-out after changing nginx IP

### ISSUE THREAD

**Issue by megatonix** [BookStackApp/BookStack#4212]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After switching nginx serwer IP address i cannot open bookstack domain.

I tried this:
```
php artisan bookstack:update-url <oldUrl> <newUrl>


```

even i deleted nginx dir

nothing happend

### Exact BookStack Version

23.02.1-ls67

### PHP Version

7.4

### Hosting Environment

Ubuntu server 22.04

**Comment by ssddanbrown** [comment]
Hi @megatonix,
I'm very confused regarding your environment. The PHP version does not match the BookStack version for the Ubuntu version. Based upon `23.02.1-ls67` it sounds like you might be using the linuxserver docker image? But that's not clear since docker is not otherwise mentioned. 

Can you confirm exactly how you installed/run BookStack?

> After switching nginx serwer IP address

What exactly do you mean by this, what IP did you change? What Nginx is this? Is that within a container? Or on a host system?

> even i deleted nginx dir

Exactly what directory did you delete? Why did you delete this?

**Comment by megatonix** [comment]
Ok so i installed bookstack on 192.168.0.10 but my nginx proxy manager was on 192.168.0.20 now i switch nginx from 192.168.0.20 to 192.169.0.10. After this a cannot load login page.

 I Deleted ngix dir in bookstack/nginx then restarted container and nginx dir recreated

**Comment by ssddanbrown** [comment]
All of this is very environment dependant, and you didn't really answer all questions. It's going to be hard for me to make advisories as I cannot get a clear picture/idea of your environment.

If you are getting a `504 Gateway Time-out`, it's likely your config within nginx-proxy-manager is wrong. You'll need to make sure this is forwarding requests to the right IP.

**Comment by megatonix** [comment]
What exatly do you need from me and where i can find that?

In my Nginx Proxy manager i point domain to IP addres where i installed Bookstack

**Comment by ssddanbrown** [comment]
- Can you still access the nginx proxy-manager interface?
- Do you host anything else using nginx proxy manager? If so, can you still access those services?
- Are you using docker-compose? If so, please provide your docker-compose yaml for BookStack.

> now i switch nginx from 192.168.0.20 to 192.169.0.10. After this a cannot load login page.

A `192.169.x.x` IP address is not within private network space, are you sure that's correct and available on your network?

**Comment by megatonix** [comment]
It's my mistake. Everything is in 192.168.x.x.

Yes i can still acces nginx proxy-manager interface
Yes everything is working fine on my nginx, like Nextcloud AIO, grafana, UptimeKuma 
My docker compose:
```
version: "3"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://book.domain.com
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=
      - DB_DATABASE=bookstackapp
    volumes:
      - ./bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=
      - TZ=Europe/Poland
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=
    volumes:
      - ./bookstack_db:/config
    restart: unless-stopped

```

On my router i only switch redirection from nginx on serwer 192.168.10.20 to nginx on serwer 192.168.0.10
