### ISSUE TITLE
How disable cors error to access /api from another domain?

### ISSUE THREAD

**Issue by sirlordt** [BookStackApp/BookStack#4289]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello i trying to access to /api from another domain using javascript in a browser but always get cors errors. 

How disable the cors?. I know this proyect is writed in php with laravel but connot found a doc it work. 

I tried with headers directive in index.php.
I tried change the app.php added allows_origins: "*",

But nothing works.

Thanks in advance.

### Exact BookStack Version

Lastest from docker hub

### PHP Version

8.0

### Hosting Environment

Docker container from docker hub

**Comment by ssddanbrown** [comment]
> I tried with headers directive in index.php.
> I tried change the app.php added allows_origins: "*",

Please avoid altering core app files, especially in the docker environment as changes will be easily lost.

I'd recommend altering/setting CORS headers at your webserver level.
You could maybe do this within the container web-server, or if you're using a proxy layer then that might be more appropriate. 

- Are you using a reverse proxy with your containers? If so, what are you using?
- What container image are you using and how are you running/managing your containers?

**Comment by sirlordt** [comment]
I use a reverse proxy haproxy (I can switch to nginx).
I am using a docker image: lscr.io/linuxserver/bookstack. (I can access it inside the container).

partial docker-compose.yaml file content:

```yml
wiki.web.server.01:
    image: lscr.io/linuxserver/bookstack
    container_name: wiki.web.server.01
    depends_on:
      - wiki.mysql.server.01
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://mydomain.com/docs/wiki
      - DB_HOST=wiki.mysql.server.01
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=super_secret
      - DB_DATABASE=WikiDB
      - TZ=America/Los_Angeles
```
