### ISSUE TITLE
Set CodeMirror Theme

### ISSUE THREAD

**Issue by Shackelford-Arden** [BookStackApp/BookStack#455]
So, I'm not overly familiar with CodeMirror but...

How would I go about setting the theme for code blocks? I see CodeMirror has quite a few themes and I'd like to be able to make use of them if possible. Is this something that I need to do on the backend?

If it s a backend option... is this something that would be added that we can change in the admin settings? Personally I'm looking at global setting as I don't really want to have to do this page to page.

**Comment by ssddanbrown** [comment]
Hi @Shackelford-Arden,

Currently the codemirror theme is hardcoded [in this file](https://github.com/BookStackApp/BookStack/blob/9126da629925a9dd7a637f3280d7e9614f48a45e/resources/assets/js/code.js#L125) with the [theme styles located here](https://github.com/BookStackApp/BookStack/blob/9126da629925a9dd7a637f3280d7e9614f48a45e/resources/assets/sass/_codemirror.scss#L357).

At the moment, you could override the styles if you wanted but you can't change the codemirror theme directly. For the purpose of keeping release CSS/JS sizes low I'd prefer not to embed all possible themes but what we could do is update the theme references in the JS files so they can be overridden using the 'custom head content' setting. Think we'd need to add some documentation at bookstackapp.com as well with an example of how someone could do this.

**Comment by domainzero** [comment]
This can currently be done with pretty low effort, but it's a little hacky. Codemirror has a repo of all their themes [here](https://codemirror.net/theme/). 

I snagged the [dracula](https://codemirror.net/theme/dracula.css) theme, changed all the instances of `dracula` to `base16-light` and loaded it into the custom head content. This way avoids a lot of fussing with the scss and other materials.

![voila](http://i.imgur.com/sEUt8VI.png)
![timestwo](http://i.imgur.com/pM2pT5L.png)

Here's my entire stylesheet:
```css
.cm-s-base16-light.CodeMirror, .cm-s-base16-light .CodeMirror-gutters {
  background-color: #282a36 !important;
  color: #f8f8f2 !important;
  border: none;
}
.cm-s-base16-light .CodeMirror-gutters { color: #282a36; }
.cm-s-base16-light .CodeMirror-cursor { border-left: solid thin #f8f8f0; }
.cm-s-base16-light .CodeMirror-linenumber { color: #6D8A88; }
.cm-s-base16-light .CodeMirror-selected { background: rgba(255, 255, 255, 0.10); }
.cm-s-base16-light .CodeMirror-line::selection, .cm-s-base16-light .CodeMirror-line > span::selection, .cm-s-base16-light .CodeMirror-line > span > span::selection { background: rgba(255, 255, 255, 0.1)!important; }
.cm-s-base16-light .CodeMirror-line::-moz-selection, .cm-s-base16-light .CodeMirror-line > span::-moz-selection, .cm-s-base16-light .CodeMirror-line > span > span::-moz-selection { background: rgba(255, 255, 255, 0.1)!important; }
.cm-s-base16-light span.cm-comment { color: #6272a4; }
.cm-s-base16-light span.cm-string, .cm-s-base16-light span.cm-string-2 { color: #f1fa8c; }
.cm-s-base16-light span.cm-number { color: #bd93f9; }
.cm-s-base16-light span.cm-variable { color: #50fa7b; }
.cm-s-base16-light span.cm-variable-2 { color: white; }
.cm-s-base16-light span.cm-def { color: #50fa7b; }
.cm-s-base16-light span.cm-operator { color: #ff79c6; }
.cm-s-base16-light span.cm-keyword { color: #ff79c6; }
.cm-s-base16-light span.cm-atom { color: #bd93f9; }
.cm-s-base16-light span.cm-meta { color: #f8f8f2; }
.cm-s-base16-light span.cm-tag { color: #ff79c6; }
.cm-s-base16-light span.cm-attribute { color: #50fa7b; }
.cm-s-base16-light span.cm-qualifier { color: #50fa7b; }
.cm-s-base16-light span.cm-property { color: #66d9ef; }
.cm-s-base16-light span.cm-builtin { color: #50fa7b; }
.cm-s-base16-light span.cm-variable-3, .cm-s-base16-light span.cm-type { color: #ffb86c; }

.cm-s-base16-light .CodeMirror-activeline-background { background: rgba(255,255,255,0.1); }
.cm-s-base16-light .CodeMirror-matchingbracket { text-decoration: underline; color: white !important; }
```

YMMV.
