### ISSUE TITLE
Datetime and TZ inconsistencies

### ISSUE THREAD

**Issue by NekoiNemo** [BookStackApp/BookStack#4786]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have the following issues and can't seem to figure out if this is a bug or a misconfiguration:

1. When mousing over elements to get the exact dates - they are in UTC regardless of user's actual TZ. Now, they are correct (as in - this is the correct UTC time of the action), the "n units ago" is calculated correctly, they are stored in the database correctly, but the exact timestamp is shown in the UI without respect for user's TZ, and without indication that time is being displayed in UTC
2. The way the exact timestamp is displayed is inconsistent:
  * For comments (as well as in Audit Log, User's last login and most other places) it displays good nice ISO timestamp: 
![screenshot_1705673074](https://github.com/BookStackApp/BookStack/assets/3595771/d33aceb9-3ab4-420a-9bf5-cc4582f1ced7)
  * For books/pages it is displayed as such: 
![screenshot_1705673002](https://github.com/BookStackApp/BookStack/assets/3595771/6d896383-56f7-41de-b9a0-0879e98321ad)
![screenshot_1705673070](https://github.com/BookStackApp/BookStack/assets/3595771/a48ac090-453c-4be1-90d5-abc7d0ccaf7f)
  * And for Recent Activity column on the left - there's no popup with a timestamp at all

### Exact BookStack Version

v23.12.1

### Hosting Environment

Docker container (from LSIO) behind NGINX

```
  server:
    image: lscr.io/linuxserver/bookstack:latest
    environment:
      TZ: UTC
      APP_TIMEZONE: UTC
      APP_LANG: en
      APP_AUTO_LANG_PUBLIC: false

  db:
    image: lscr.io/linuxserver/mariadb:10.11.5
    environment:
      TZ: UTC
```

Host server is also in UTC (though it's locale isn't bound into containers)
