### ISSUE TITLE
Database volume not mounting

### ISSUE THREAD

**Issue by need4swede** [BookStackApp/BookStack#4883]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Windows 11, setup via Docker-Compose.
I am not a Docker expert by any means, but for some reason my database volume isn't being binded to my host, but the app config manages to do so just fine.

I had some issues getting it all working with MariaDB at first, but I was able to get it working by switching to MySQL instead. But for some reason, the database volume ends up in the container, rather than on my host PC. I've tried removing everything and doing a fresh install of BookStackApp, but the problem persists. Is this a bug, or am I slipping up somewhere? Thank you!

```
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=<my_url>
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=<user>
      - DB_PASS=<password>
      - DB_DATABASE=bookstackapp
    volumes:
      - B:\Apps\bookstackapp\config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: mysql:8.0.32
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<password>
      - TZ=US/Pacific
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=<user>
      - MYSQL_PASSWORD=<password>
    volumes:
      - B:\Apps\bookstackapp\database:/config
    restart: unless-stopped
```

### Exact BookStack Version

v24.02

### Hosting Environment

Windows 11, installed via Docker-Compose file (see description)
