### ISSUE TITLE
Trying to deploy bookstack

### ISSUE THREAD

**Issue by PJTharpeNoob** [BookStackApp/BookStack#5283]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello! New to bookstack and Linux as a whole I guess, but have been in IT for 20 years.
I am trying to deploy bookstack via docker.
I am using Ubuntu 22.04 with aaPanel with Nginx 1.24, MySQL 8.0.35, PHPMyadmin 5.2 and PHP 8.0

Here is my docker-compose.yml file:

```yml
---
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - APP_URL=http://localhost:6875
      - APP_KEY=2zdwi8n9D/8ytUmWhBae6GO6X9GtqRAXwFw9XxQJicM=
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USERNAME=bookstack
      - DB_PASSWORD=password
      - DB_DATABASE=bookstackapp
    volumes:
      - /var/docker-data/bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=password
    volumes:
      - /var/docker-data/bookstack_db_data:/config
    restart: unless-stopped
```

When I run the composer, it gets to this and stops:

<img width="775" alt="image" src="https://github.com/user-attachments/assets/0b0c1c2a-1d60-4054-8176-72ffe1f8e177">

Any help would be appreciated. I have been scouring the internet for the last 2 days and cant figure this out :(

Thank you!

### Exact BookStack Version

10.11.8

### Hosting Environment

I am using Ubuntu 22.04 with aaPanel with Nginx 1.24, MySQL 8.0.35, PHPMyadmin 5.2 and PHP 8.0
