### ISSUE TITLE
Bookstack fails to send email through relay

### ISSUE THREAD

**Issue by KCKgithub** [BookStackApp/BookStack#5366]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

When sending a test email to an open, internal relay with no encryption, email fails to send.
![image](https://github.com/user-attachments/assets/dee4747c-b2f3-4c3d-9c14-8303ae4c263c)

### Exact BookStack Version

v24.10.3

### Log Content

Nothing pertaining to email failure in any log file.   APP_DEBUG=true does not display errors.

/var/lib/nginx/logs
/app/www/storage/logs
/app/www/vendor/aws/aws-sdk-php/src/data/logs

### Hosting Environment

Kubernetes v1.31.2+k3s1 using the image provided by linuxserver linuxserver/bookstack:latest
Container is able to resolve the mail relay.
There is no authentication or encryption required (or enabled) to use the relay.  Strictly old-timey port 25 only.

I'm at a lost since this is about as simple as an email relay can get.

<details><summary>Details</summary>
<p>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack-tech
  namespace: bookstack-tech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack-tech
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bookstack-tech
    spec:
      containers:

      - name: bookstack-tech
        image: linuxserver/bookstack:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/Chicago
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: APP_URL
          value: "XXXXXXXX"
        - name: APP_KEY
          value: "XXXXXXXX"
        - name: DB_HOST
          value: "XXXXXXXX"
        - name: DB_PORT
          value: "3306"
        - name: DB_USERNAME
          value: "XXXXXXXX"
        - name: DB_PASSWORD
          value: "XXXXXXXX"
        - name: DB_DATABASE
          value: "XXXXXXXX"
        - name: MAIL_DRIVER
          value: "smtp"
        - name: MAIL_FROM_NAME
          value: "STUFF Admin"
        - name: MAIL_FROM
          value: "XXXXXXXXX"
        - name: MAIL_HOST
          value: 'mail.XXXX.XXX'
        - name: MAIL_PORT
          value: '25'
#        - name: APP_DEBUG
#          value: "false"
        ports:
          - containerPort: 6875
            protocol: TCP

        volumeMounts:
        - name: bookstack-tech-claim0
          mountPath: "/config"

      volumes:
        - name: bookstack-tech-claim0
          persistentVolumeClaim:
            claimName: bookstack-tech-claim0
```

</p>
</details> 

I also tried editing the values in .env directly within the container, no change in behavior.   I will include them in the spirt of being thorough.

```bash
# Mail system to use
# Can be 'smtp' or 'sendmail'
MAIL_DRIVER=smtp

# Mail sender details
MAIL_FROM_NAME="STUFF Admin"
MAIL_FROM=noreply@XXXX.com

# SMTP mail options
# These settings can be checked using the "Send a Test Email"
# feature found in the "Settings > Maintenance" area of the system.
# For more detailed documentation on mail options, refer to:
# https://www.bookstackapp.com/docs/admin/email-webhooks/#email-configuration
MAIL_HOST=mail.XXXX.com
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_VERIFY_SSL=false
```

![email-error](https://github.com/user-attachments/assets/cc21b54f-2351-45a2-9dc0-394542c63867)
