### ISSUE TITLE
bookstack after upg doesn't work

### ISSUE THREAD

**Issue by balgerion** [BookStackApp/BookStack#5433]
### Attempted Debugging

- [x] I have read the debugging page

### Searched GitHub Issues

- [x] I have searched GitHub for the issue.

### Describe the Scenario

Good morning,

Yesterday my bookstack updated (it have latest tag on it)  

![Image](https://github.com/user-attachments/assets/253eb6e1-086b-4191-b529-f4fd7174a70c)
and i wake up with this: :)

![Image](https://github.com/user-attachments/assets/f5e40f6e-f59f-4338-86ae-f9cfedaaca28)

there is no error in logs and i dont see any braking changes on github notes. 

![Image](https://github.com/user-attachments/assets/cac65953-4b4f-46b7-953b-d4b5d1fc56cc)

docker compose:

services:
  bookstack:
    image: linuxserver/bookstack:arm64v8-latest
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
    - APP_DEBUG=true
    - PUID=1001
    - PGID=988
    - DB_HOST=192.168.1.21
    - DB_PORT=3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=
    - DB_PASSWORD=""
    - APP_URL=https://wiki.balgeriada.com
    - APP_KEY=
    - CACHE_DRIVER=database
    - SESSION_DRIVER=database
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage:/var/www/bookstack/storage/uploads
    ports:
    - "8186:80"

volumes:
  uploads:
    driver_opts:
       type: nfs
       o: nfsvers=4.2,addr=192.168.1.21       
       device: ":/mnt/Balgeriada1/docker/app/bookstack/uploads" 
  storage:
    driver_opts:
       type: nfs
       o: nfsvers=4.2,addr=192.168.1.21       
       device: ":/mnt/Balgeriada1/docker/app/bookstack/storage" 

### Exact BookStack Version

v24.12.1-ls189

### Hosting Environment

Docker , docker swarm

**Comment by ssddanbrown** [comment]
Hi @balgerion,
Those are not the expected/intended volume mounts for that container image.

Before anything, be super careful about any changes you make. There's a high potential of data loss.
Backup any storage volumes involved, and maybe the running container data too if existing and/or snapshot/backup the host machine.

The linuxserver image manages things so there's only a single `/config` volume mount-point to use/manage.
Ideally you should switch over to following the expected convention for the image.
You may need to move existing data.
There's a location mapping in the readme of that container image: https://github.com/linuxserver/docker-bookstack?tab=readme-ov-file#bookstack-file--directory-paths

**Comment by balgerion** [comment]
oohhh you are right but it was working for almost month without issue :). Changed to proper config and still have simillar error 

Btw thank you for your help and time

![Image](https://github.com/user-attachments/assets/6326f593-7e90-443f-a674-bb5027aa55c8)

files in correct place:

![Image](https://github.com/user-attachments/assets/9a202880-0394-4cfc-9e2f-7b1cf7abd961)

docker compose:
services:
  bookstack:
    image: linuxserver/bookstack:arm64v8-latest
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
    - APP_DEBUG=true
    - PUID=1001
    - PGID=988
    - DB_HOST=192.168.1.21
    - DB_PORT=3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=
    - DB_PASSWORD=""
    - APP_URL=https://wiki.balgeriada.com
    - APP_KEY=
    - CACHE_DRIVER=database
    - SESSION_DRIVER=database
    volumes:
    - config:/config
    ports:
    - "8186:80"


volumes:
  config:
    driver_opts:
       type: nfs
       o: nfsvers=4.2,addr=192.168.1.21       
       device: ":/mnt/Balgeriada1/docker/app/bookstack/config"

**Comment by tfeldmann** [comment]
Having the same problem here:

```yaml
 bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: https://...
      DB_HOST: bookstack_db
      DB_PORT: 3306
      DB_USER: bookstack
      FILE__DB_PASS: /run/secrets/bookstack_db_pass
      DB_DATABASE: bookstackapp
    secrets:
      - bookstack_db_pass
    restart: unless-stopped
    volumes:
      - bookstack_app_data:/config
    networks:
      - bookstack
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=/run/secrets/bookstack_db_pass
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=/run/secrets/bookstack_db_pass
    secrets:
      - bookstack_db_pass
    restart: unless-stopped
    volumes:
      - bookstack_db_data:/config
    networks:
      - bookstack
```

Found this in the container logs:
```
bookstack  | using keys found in /config/keys
bookstack  | **** The following active confs have different version dates than the samples that are shipped. ****
bookstack  | **** This may be due to user customization or an update to the samples. ****
bookstack  | **** You should compare the following files to the samples in the same folder and update them. ****
bookstack  | **** Use the link at the top of the file to view the changelog. ****
bookstack  | ┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
bookstack  | │  old date  │  new date  │ path                                                                   │
bookstack  | ├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
bookstack  | │ 2023-12-25 │ 2024-07-16 │ /config/nginx/site-confs/default.conf                                  │
bookstack  | │ 2023-04-13 │ 2024-12-17 │ /config/nginx/nginx.conf                                               │
bookstack  | │ 2023-08-13 │ 2024-12-06 │ /config/nginx/ssl.conf                                                 │
bookstack  | └────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
bookstack  | Waiting for DB to be available
```

But using the newer .conf files didn't change anything.
Found no errors in nginx or bookstack logs. How can I debug this?

**Comment by ssddanbrown** [comment]
I'll spin up a fresh stack myself to check it's not something baked into the image.

@tfeldmann Are you also running on ARM?

**Comment by ssddanbrown** [comment]
A fresh stack on standard x86_64 seems to work okay.

<details><summary>Full compose</summary>
<p>

```yml
---
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack_20250121
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - APP_URL=http://localhost:6875
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USERNAME=bookstack
      - DB_PASSWORD=dbpass
      - DB_DATABASE=bookstackapp
      - APP_KEY=base64:HPTxCk+r+a8ly2S7tJG7ItNiJlJLr9mzT0t67FrcXIw=
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
    

  bookstack_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack_db_20250121
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=dbpass
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=dbpass
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
```

</p>
</details>
