### ISSUE TITLE
bookstack-system-cli restore fails

### ISSUE THREAD

**Issue by wiknesta** [BookStackApp/BookStack#5489]
### Describe the Bug

Use the system cli to execute a restore. For example:
_/app/www/bookstack-system-cli restore /backups/bookstack.zip_

Now the process fails with the following message:
_Extracting ZIP into temporary directory...
Restoring and merging .env file...

An error occurred when attempting to run a command:

Could not find a working database configuration_

### Steps to Reproduce

Use the system cli to execute a restore
For example: /app/www/bookstack-system-cli restore /backups/bookstack.zip

### Expected Behaviour

The restore ends with the message: "Restore operation complete"

### Screenshots or Additional Context

We use a Docker installation (lscr.io/linuxserver/bookstack). The restore is executed in the docker container of bookstack.
If bookstack is reset to version 24.05.3, the same restore works without any problems.

### Exact BookStack Version

v24.12.1

**Comment by ssddanbrown** [comment]
Hi @wiknesta,
The CLI will throw that error if it can't find a working database connect from details it finds.

- In this environment, where exactly would working database connection details be found?
- Is the database running and connectable during this attempted restore?

**Comment by wiknesta** [comment]
Hi @ssddanbrown
This problem may be related to issue #5373 (backup)

The database is running and connectable during this attempted restore. 
Bookstack is installed with the folling docker-compose.yml:

```
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://192.168.1.136:6875
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=dummypassword
      - DB_DATABASE=bookstackapp
      - TZ=Europe/Zurich
      
    volumes:
      - /home/xabano/docker/bookstack_app_data:/config
      - /etc/localtime:/etc/localtime:ro 
    ports:
      - 6875:80
    restart: always
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=dummypassword
      - TZ=Europe/Zurich
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=dummypassword
    volumes:
      - /home/xabano/docker/bookstack_db_data:/config
      - /etc/localtime:/etc/localtime:ro 

    restart: unless-stopped
```

If an older docker-image is used for bookstack, there is no error.  In this case, the restore is carried out correctly
