### ISSUE TITLE
500 Internal Server Error on Synology

### ISSUE THREAD

**Issue by QuentinCaldeira** [BookStackApp/BookStack#5557]
### Attempted Debugging

- [x] I have read the debugging page

### Searched GitHub Issues

- [x] I have searched GitHub for the issue.

### Describe the Scenario

Hi,
I follow the docker-compose template. Here is mine :

```
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    networks:
      network:
        ipv4_address: 192.168.46.2
    container_name: bookstack
    environment:
      - PUID=1032
      - PGID=100
      - TZ=Europe/Paris
      - APP_URL=http://192.168.1.61:6875
      - APP_KEY=base64:Gw*******************************/HKi6gw=

      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=bookstack8432
    volumes:
      - ./config:/config:rw
    ports:
      # This exposes port 6875 for general web access.
      # Commonly you'd have a reverse proxy in front of this,
      # redirecting incoming requests to this port.
      - 6875:80
    restart: unless-stopped

  # The container for the database which BookStack will use to store
  # most of its core data/content.
  mariadb:
    # You should update the version here to match the latest
    # main version of the linuxserver mariadb container version:
    # https://github.com/linuxserver/docker-mariadb/pkgs/container/mariadb/versions?filters%5Bversion_type%5D=tagged
    image: lscr.io/linuxserver/mariadb:11.4.4
    networks:
      network:
        ipv4_address: 192.168.46.3
    container_name: mariadb
    environment:
      - PUID=1032
      - PGID=100
      - TZ=Europe/Paris
      # You may want to change the credentials used below,
      # but be aware the latter three options need to align
      # with the DB_* options for the BookStack container.
      - MYSQL_ROOT_PASSWORD=mysupersecretrootpassword
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack8432
    volumes:
      # You generally only ever need to map this one volume.
      # This maps it to a "bookstack_db_data" folder in the same
      # directory as this compose config file.
      - ./config:/config:rw

    # These ports are commented out as you don't really need this port
    # exposed for normal use, mainly only if connecting direct the the
    # database externally. Otherwise, this risks exposing access to the
    # database when not needed.
    # ports:
    #   - 3306:3306
    restart: unless-stopped

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.46.0/29"
```
It's a fresh new install, no db migration. I have checked that the user have access to the config repository. Idk if it's a permission issue. Any clue ?

![Image](https://github.com/user-attachments/assets/9fea36e5-2987-4efa-ba93-6530cf753afa)

### Exact BookStack Version

latest

### Log Content

[laravel.log](https://github.com/user-attachments/files/19476031/laravel.log)

[mariadb-error.log](https://github.com/user-attachments/files/19476032/mariadb-error.log)

[access.log](https://github.com/user-attachments/files/19476034/access.log)
[error.log](https://github.com/user-attachments/files/19476035/error.log)

[error.log](https://github.com/user-attachments/files/19476037/error.log)

### Hosting Environment

Docker compose on a Synology. Localhost only, access via http://myip:6875
