### ISSUE TITLE
mariadb creates a lot of error-files

### ISSUE THREAD

**Issue by towerplease** [BookStackApp/BookStack#5671]
### Describe the Bug

Hi there,

i recently noticed, that the mariadb-container within the bookstack-docker-stack is producing *.err files.
The error seems to be inconsintent, as this does not appear every day. 
Bookstack functions properly, as of now i cannot see any errors on the front end.

I use a docker compose stack, as of the multitple examples given.
The mariadb-database is bind-mounted to a local directory and i wondered why this is so big (>6 GB)
After investigating, i found some *.err files with some if them are bigger than 200 MB.
The error in there always repeats:
`2025-06-23 15:32:12 953 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
2025-06-23 15:32:12 954 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').`

My docker-compose file:

<details><summary>Details</summary>
<p>

```yml
---
services:
 bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    # Arbeitsspeicher limit
    mem_limit: 1g
    # Priorisierung - 1024 = Default
    cpu_shares: 1024
    environment:
    # Konfiguration über .env File in app_data/www/.env
      - PUID=1000
      - PGID=1000
      - APP_URL=https://sub.domain.tld
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - /mnt/docker/volume/bookstack/app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
 bookstack_db:
    image: lscr.io/linuxserver/mariadb
    # Arbeitsspeicher limit
    mem_limit: 500m
    # Priorisierung - 1024 = Default
    cpu_shares: 1024
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /mnt/docker/volume/bookstack/db_data:/config
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

</p>
</details> 

it looks like this in the folder:

![Image](https://github.com/user-attachments/assets/cd80340b-5190-48b8-898d-efe1db31581b)

Hopefully this help to resolve the issue.

### Steps to Reproduce

deploy via docker compose
inspect maria-db folder after a while of use.

### Expected Behaviour

No creation of such error files. Or alternativly rotating error-files.

### Browser Details

firefox/chrome

### Exact BookStack Version

25.05.1
