### ISSUE TITLE
NGINX Reverse Proxy Issue (Working Config Example Requested)

### ISSUE THREAD

**Issue by lithium-ap** [BookStackApp/BookStack#611]
### For Bug Reports

* BookStack Version 0.18.5 (docker image)
* PHP Version: 7.1
* MySQL Version: 5.6

##### Expected Behavior

NGINX provides SSL services for domain name. 

##### Current Behavior

502 Gateway timeout at doc.example.com

##### Config Info
docker-compose.yml:
```
`version: '2'
services:

  bookstack:
    image: solidnerd/bookstack:0.18.5
    environment:
    - DB_HOST=*LAN IP*:3306
    - DB_DATABASE=docsrv
    - DB_USERNAME=docsrv
    - DB_PASSWORD=[REDACTED]
    - APP_URL=https://doc.mydomain.net (this has been tested with or without)
    volumes:
    - /mnt/container_data/5docsrv/uploads:/var/www/bookstack/public/uploads
    - /mnt/container_data/5docsrv/storage-uploads:/var/www/bookstack/public/storage
    ports:
    - "8090:80"
```
nginx conf file

```
upstream docsrv {
    server 127.0.0.1:8090 fail_timeout=0;
}

server {
    listen 80;
    listen [::]:80;

    server_name doc.mydomain.net;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443;

    server_name doc.mydomain.net;

    ssl_certificate /etc/nginx/certs/issued_certs/doc.mydomain.net/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/issued_certs/doc.mydomain.net/privkey.pem;

    location /.well-known {
        root /etc/nginx/certs/well_known/doc.mydomain.net/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8090;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 900s;
    }
}
```
